"""Collator for forecasting batches that train the linear forecast head.

Differs from :class:`timeomni_v.data.collator.TimeOmniVDataCollator` in three ways:

1. Builds a *user-only* conversation (``answer=None``). The forecast head
   replaces text generation, so we never need an assistant turn — saves the
   trailing ``<|im_start|>assistant\\n...<|im_end|>\\n`` template tokens
   from the prompt.
2. Loads ``forecast_target_path`` (single-channel CSV) for each sample,
   right-pads with NaN to ``pred_len``, and emits ``forecast_target``
   (``(B, pred_len)`` float32) plus ``forecast_target_mask`` (bool) so the
   model can compute MSE only on real timesteps.
3. Sets ``labels`` to ``None`` (HF Trainer will skip CE loss; the model
   returns the head's MSE loss instead).

Asserts every row is single-channel (``ts_shape[1] == 1``) and
``task == "prediction"``. The single-channel invariant is the contract
established by ``timeomni_v.data.convert_per_channel_forecasting``.
"""

from __future__ import annotations

import time
from dataclasses import dataclass
from pathlib import Path

import numpy as np
import pandas as pd
import torch

from timeomni_v.data.chat_format import apply_template_and_mm, build_conversation
from timeomni_v.data.collator import (
    DEFAULT_FPS,
    DEFAULT_IMAGE_MAX_PIXELS,
    DEFAULT_IMAGE_MIN_PIXELS,
    DEFAULT_VIDEO_MAX_PIXELS,
    DEFAULT_VIDEO_MIN_PIXELS,
    DEFAULT_DO_SAMPLE_FRAMES,
    DEFAULT_MAX_FRAMES,
    DEFAULT_MIN_FRAMES,
    _log_collator_timing,
    strip_ts_block,
)
from timeomni_v.processing.processing_timeomni_v import TimeOmniVProcessor


def _load_target_csv(path: str) -> np.ndarray:
    """Load a single-channel forecast target CSV → ``(T_target,)`` float32.

    Mirrors :func:`load_and_pad_ts_csvs`'s ``timestamp``-drop behavior so
    targets generated by ``convert_per_channel_forecasting`` (which keeps
    only the value column) and any external CSVs that include a timestamp
    column both work.
    """
    df = pd.read_csv(path)
    if "timestamp" in df.columns:
        df = df.drop(columns=["timestamp"])
    if df.shape[1] != 1:
        raise ValueError(
            f"forecast_target_path={path!r} must be single-channel; "
            f"got shape={df.shape}"
        )
    return df.to_numpy(dtype=np.float32).reshape(-1)  # (T_target,)


@dataclass
class ForecastCollator:
    processor: TimeOmniVProcessor
    pred_len: int
    fps: float = DEFAULT_FPS
    video_min_pixels: int = DEFAULT_VIDEO_MIN_PIXELS
    video_max_pixels: int = DEFAULT_VIDEO_MAX_PIXELS
    image_min_pixels: int = DEFAULT_IMAGE_MIN_PIXELS
    image_max_pixels: int = DEFAULT_IMAGE_MAX_PIXELS
    do_sample_frames: bool = DEFAULT_DO_SAMPLE_FRAMES
    max_frames: int = DEFAULT_MAX_FRAMES
    min_frames: int = DEFAULT_MIN_FRAMES
    log_timing: bool = False

    def __call__(self, batch: list[dict]) -> dict:
        if self.processor.tokenizer.padding_side != "right":
            raise ValueError(
                f"ForecastCollator requires tokenizer.padding_side='right', "
                f"got {self.processor.tokenizer.padding_side!r}."
            )
        if self.pred_len <= 0:
            raise ValueError(f"ForecastCollator.pred_len must be > 0, got {self.pred_len}")

        t0 = time.perf_counter() if self.log_timing else 0.0
        full_texts: list[str] = []
        all_videos: list = []
        all_images: list = []
        ts_paths: list[str] = []
        target_arrs: list[np.ndarray] = []
        target_lens: list[int] = []

        for row in batch:
            if row.get("task") != "prediction":
                raise ValueError(
                    f"ForecastCollator received non-prediction row "
                    f"(id={row.get('id')!r}, task={row.get('task')!r})."
                )
            ts_path = row.get("timeseries_path")
            if ts_path is None:
                raise ValueError(
                    f"ForecastCollator row id={row.get('id')!r} missing timeseries_path."
                )
            target_path = row.get("forecast_target_path")
            if target_path is None:
                raise ValueError(
                    f"ForecastCollator row id={row.get('id')!r} missing "
                    "forecast_target_path. Run convert_per_channel_forecasting first."
                )
            tgt = _load_target_csv(target_path)
            if tgt.shape[0] > self.pred_len:
                raise ValueError(
                    f"row id={row.get('id')!r}: target length {tgt.shape[0]} > "
                    f"pred_len={self.pred_len}; raise --pred_len."
                )
            target_arrs.append(tgt)
            target_lens.append(int(tgt.shape[0]))

            # Forecasting batches go through the head, never the LM head —
            # the empty assistant turn (answer="") matches what
            # convert_per_channel_forecasting wrote to the jsonl and what
            # length_estimate.compute_exact_lengths counts, so the
            # token-budget sampler stays in sync. The few template tokens
            # of the empty assistant turn are harmless: labels=None so they
            # contribute nothing to the loss.
            conv_full = build_conversation(
                row,
                answer=row.get("answer", ""),
                fps=self.fps,
                max_frames=self.max_frames,
                min_frames=self.min_frames,
                video_min_pixels=self.video_min_pixels,
                video_max_pixels=self.video_max_pixels,
                image_min_pixels=self.image_min_pixels,
                image_max_pixels=self.image_max_pixels,
                include_timeseries=True,
                prompt_transform=strip_ts_block,
            )
            full_text, _, images, videos = apply_template_and_mm(
                self.processor, conv_full, add_generation_prompt=False,
            )
            full_texts.append(full_text)
            all_videos.extend(videos or [])
            all_images.extend(images or [])
            ts_paths.append(ts_path)
        t_prep = time.perf_counter() if self.log_timing else 0.0

        batch_out = self.processor(
            text=full_texts,
            videos=all_videos or None,
            images=all_images or None,
            timeseries=ts_paths,
            videos_kwargs={
                "size": {
                    "shortest_edge": self.video_min_pixels,
                    "longest_edge": self.video_max_pixels,
                },
            },
            images_kwargs={
                "min_pixels": self.image_min_pixels,
                "max_pixels": self.image_max_pixels,
            },
            return_tensors="pt",
            padding=True,
        )
        t_proc = time.perf_counter() if self.log_timing else 0.0

        # Build (B, pred_len) padded target and mask.
        bs = len(batch)
        target = torch.full((bs, self.pred_len), float("nan"), dtype=torch.float32)
        mask = torch.zeros((bs, self.pred_len), dtype=torch.bool)
        for i, (arr, n) in enumerate(zip(target_arrs, target_lens)):
            target[i, :n] = torch.from_numpy(arr)
            mask[i, :n] = True
        batch_out["forecast_target"] = target
        batch_out["forecast_target_mask"] = mask
        batch_out["forecast_target_lens"] = torch.tensor(target_lens, dtype=torch.long)
        # Drop labels — HF Trainer dispatches CE loss when labels is present.
        batch_out["labels"] = None

        if self.log_timing:
            t_lbl = time.perf_counter()
            from timeomni_v.utils.tokens import TS_PLACEHOLDER
            tok = self.processor.tokenizer
            vpad_id = tok.convert_tokens_to_ids(tok.video_token)
            ipad_id = tok.convert_tokens_to_ids(tok.image_token)
            ts_pad_id = tok.convert_tokens_to_ids(TS_PLACEHOLDER)
            _log_collator_timing(
                "FORECAST_COLLATOR",
                batch_out["input_ids"], batch_out["attention_mask"], vpad_id,
                t0=t0, t_prep=t_prep, t_proc=t_proc, t_lbl=t_lbl,
                ts_pad_id=ts_pad_id, ipad_id=ipad_id,
            )
        return batch_out


__all__ = ["ForecastCollator"]
